[package]
description = "High-performance modern Wilkinson's formula parsing for statistical models. Parses R-style formulas into structured JSON metadata supporting linear models, mixed effects, and complex statistical specifications."
name = "fiasto"
version = "0.2.0"
edition = "2021"
authors = ["Alex Hallam <alexhallam6.28@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/alexhallam/fiasto"
repository = "https://github.com/alexhallam/fiasto"
documentation = "https://docs.rs/fiasto"
keywords = [
    "regression",
    "formula-parser",
    "formulaic",
    "wilkinson",
    "r-formula",
]
categories = ["science", "data-structures", "parsing", "text-processing"]
rust-version = "1.89.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
logos = "0.15.1"
